# Read MAJOR/MINOR/PATCH from version.txt and expose APP_FIRMWARE_VERSION.
function(read_firmware_version version_file out_version_var)
    if(NOT EXISTS "${version_file}")
        message(FATAL_ERROR "Version file not found: ${version_file}")
    endif()

    set(_major "")
    set(_minor "")
    set(_patch "")

    file(STRINGS "${version_file}" _lines)
    foreach(_line IN LISTS _lines)
        string(STRIP "${_line}" _line)
        if(_line STREQUAL "" OR _line MATCHES "^#")
            continue()
        endif()
        if(_line MATCHES "^MAJOR=([0-9]+)$")
            set(_major ${CMAKE_MATCH_1})
        elseif(_line MATCHES "^MINOR=([0-9]+)$")
            set(_minor ${CMAKE_MATCH_1})
        elseif(_line MATCHES "^PATCH=([0-9]+)$")
            set(_patch ${CMAKE_MATCH_1})
        else()
            message(FATAL_ERROR "Invalid version line in ${version_file}: ${_line}")
        endif()
    endforeach()

    if(_major STREQUAL "" OR _minor STREQUAL "" OR _patch STREQUAL "")
        message(FATAL_ERROR "version.txt must define MAJOR, MINOR and PATCH")
    endif()

    set(${out_version_var} "${_major}.${_minor}.${_patch}" PARENT_SCOPE)
endfunction()
